version: '3'

dotenv: ['.env', '.env.test']

vars:
  LOCAL_SERVICES: "kafka schema-registry postgres product"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  STOP_CMD: "docker-compose down -v"
  LOGS_CMD: "docker-compose logs -f --tail=500"
  BASH_PRODUCT_CMD: "docker exec -it product-app sh"
  LOGS_PRODUCT_CMD: "docker-compose logs -f --tail=500 product-app"

tasks:
  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'
  build:
    desc: Build container
    cmds:
      - '{{.BUILD_CMD}}'
  stop:
    desc: Stop env
    cmds:
      - '{{.STOP_CMD}}'
  product:
    desc: Enter movie bash
    cmds:
      - '{{.BASH_PRODUCT_CMD}}'
  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'
  logs:product:
    desc: Docker product logs
    cmds:
      - '{{.LOGS_PRODUCT_CMD}}'
