@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for POC - Schema Registry

Container(product, "Product App", "Django", "API that represents all its products", $tags="v0.1")
Container(supplier, "Supplier App", "FastAPI", "API that represents all its suppliers", $tags="v0.1")

Rel(product, supplier, "talk to", "kafka")

@enduml
